### ISSUE TITLE
unable to build with go 1.7.4

### ISSUE THREAD

**Issue by deadc0de6** [zmap/zgrab#295]
I need help to build zgrab on debian stretch:
```
$ export GOPATH=$HOME/go
$ mkdir -p $GOPATH
$ go env GOPATH
/home/user/go
$ which go
/usr/bin/go
$ go version
go version go1.7.4 linux/amd64
$ go get github.com/zmap/zgrab
# github.com/zmap/zgrab/ztools/http
go/src/github.com/zmap/zgrab/ztools/http/client.go:314: undefined: time.Until
go/src/github.com/zmap/zgrab/ztools/http/fs.go:80: undefined: sort.Slice
go/src/github.com/zmap/zgrab/ztools/http/transport.go:579: treq.Request.URL.Port undefined (type *url.URL has no field or method Port)
go/src/github.com/zmap/zgrab/ztools/http/transport.go:587: cm.proxyURL.Port undefined (type *url.URL has no field or method Port)
go/src/github.com/zmap/zgrab/ztools/http/transport.go:1993: url.Hostname undefined (type *url.URL has no field or method Hostname)
go/src/github.com/zmap/zgrab/ztools/http/transport.go:1997: url.Port undefined (type *url.URL has no field or method Port)
```

Thanks

**Comment by deadc0de6** [comment]
duplicate from #294
